export enum ActionTypes {
  ON_APP_LOAD = 'ON_APP_LOAD',
  ON_LOGIN = 'ON_LOGIN',
  ON_INITIATE_SIGNUP = 'ON_INITIATE_SIGNUP',
  ON_VERIFY_SIGNUP_EMAIL = 'ON_VERIFY_SIGNUP_EMAIL',
  SET_SIGNUP_FLOW_CREDENTIALS = 'SET_SIGNUP_FLOW_CREDENTIALS',
  SET_APP_INITIALIZED = 'APP_INITIALIZED',
  SET_APP_LOADING = 'SET_APP_LOADING',
  SET_APP_ERROR = 'SET_APP_ERROR',
  SET_APP_INFO = 'SET_APP_INFO',
  CLOSE_SNACKBAR = 'CLOSE_SNACKBAR',
  SET_USER_DATA = 'SET_USER_DATA',
  SET_ARTICLES = 'SET_ARTICLES',
  ON_SELECT_ARTICLE = 'ON_SELECT_ARTICLE',
  ON_SET_IS_PLAYING = 'ON_SET_IS_PLAYING',
  ON_PLAY = 'ON_PLAY',
  ON_PAUSE = 'ON_PAUSE',
  SET_ARTICLE = 'SET_ARTICLE',
  TOGGLE_PLAYER_MODAL = 'TOGGLE_PLAYER_MODAL',
  SET_PLAYBACK_PROGRESS = 'SET_PLAYBACK_PROGRESS',
  SET_SEEKING_VALUE = 'SET_SEEKING_VALUE',
  SET_PLAYLISTS = 'SET_PLAYLISTS',
  SET_ADD_PLAYLIST_MODAL_OPEN = 'SET_ADD_PLAYLIST_MODAL_OPEN',
  ON_CREATE_PLAYLIST = 'ON_CREATE_PLAYLIST',
  SET_ADD_TO_PLAYLIST_MODAL_OPEN = 'SET_ADD_TO_PLAYLIST_MODAL_OPEN',
  ON_ADD_TO_PLAYLIST = 'ON_ADD_TO_PLAYLIST',
  SET_PLAYLIST_ITEM_ADDED = 'SET_PLAYLIST_ITEM_ADDED',
  SET_SELECTED_PLAYLIST = 'SET_SELECTED_PLAYLIST',
  ON_NEXT = 'ON_NEXT',
  ON_PREVIOUS = 'ON_PREVIOUS',
  OPEN_PLAYLIST_OPTIONS_MODAL = 'OPEN_PLAYLIST_OPTIONS_MODAL',
  ON_DELETE_PLAYLIST = 'ON_DELETE_PLAYLIST',
  CLOSE_PLAYLIST_OPTIONS_MODAL= 'CLOSE_PLAYLIST_OPTIONS_MODAL',
  OPEN_PLAYLIST_ITEM_OPTIONS_MODAL = 'OPEN_PLAYLIST_ITEM_OPTIONS_MODAL',
  ON_DELETE_PLAYLIST_ITEM = 'ON_DELETE_PLAYLIST_ITEM',
  CLOSE_PLAYLIST_ITEM_OPTIONS_MODAL= 'CLOSE_PLAYLIST_ITEM_OPTIONS_MODAL',
};

interface ActionReturn<T> {
  type: string;
  payload: T;
}

export type Action<T> = (payload: T) => ActionReturn<T>;
export type ActionNoPayload = () => { type: string }
